#!/bin/sh
# stash unstaged changes, run release task, stage release updates and restore stashed files

# TODO: Unused pre-commit hook - bootstrap with husky and "npm prepare" script

NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ $NAME != '(no branch)' ]
then
  NOT_STAGED=$(git status | grep 'not staged')
  # if [ "${NOT_STAGED#*not staged}" != "$NOT_STAGED" ]
  if [ "$NOT_STAGED" != "" ]
  then
    echo "Unclean directory, aborting commit. Run git status."
    exit 1
  fi

  npm test
  RETVAL=$?

  if [ $RETVAL -ne 0 ]
  then
  	echo "tests failed, aborting commit. Run npm test"
  	exit 1
  fi
fi